Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openai in /home/at4932/.local/lib/python3.8/site-packages (0.27.2)
Requirement already satisfied: tqdm in /home/at4932/.local/lib/python3.8/site-packages (from openai) (4.64.1)
Requirement already satisfied: aiohttp in /home/at4932/.local/lib/python3.8/site-packages (from openai) (3.8.4)
Requirement already satisfied: requests>=2.20 in /share/apps/anaconda3/2020.07/lib/python3.8/site-packages (from openai) (2.24.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /home/at4932/.local/lib/python3.8/site-packages (from aiohttp->openai) (3.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/at4932/.local/lib/python3.8/site-packages (from aiohttp->openai) (6.0.4)
Requirement already satisfied: aiosignal>=1.1.2 in /home/at4932/.local/lib/python3.8/site-packages (from aiohttp->openai) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /share/apps/anaconda3/2020.07/lib/python3.8/site-packages (from aiohttp->openai) (19.3.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/at4932/.local/lib/python3.8/site-packages (from aiohttp->openai) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in /home/at4932/.local/lib/python3.8/site-packages (from aiohttp->openai) (1.3.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/at4932/.local/lib/python3.8/site-packages (from aiohttp->openai) (1.8.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /share/apps/anaconda3/2020.07/lib/python3.8/site-packages (from requests>=2.20->openai) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /share/apps/anaconda3/2020.07/lib/python3.8/site-packages (from requests>=2.20->openai) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /share/apps/anaconda3/2020.07/lib/python3.8/site-packages (from requests>=2.20->openai) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /share/apps/anaconda3/2020.07/lib/python3.8/site-packages (from requests>=2.20->openai) (2020.6.20)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-dotenv in /home/at4932/.local/lib/python3.8/site-packages (1.0.0)
  0%|          | 0/1000 [00:00<?, ?it/s]  0%|          | 1/1000 [01:37<27:01:58, 97.42s/it]  0%|          | 2/1000 [03:16<27:19:48, 98.59s/it]  0%|          | 3/1000 [04:58<27:38:13, 99.79s/it]  0%|          | 4/1000 [06:40<27:53:53, 100.84s/it]  0%|          | 5/1000 [08:24<28:09:09, 101.86s/it]  1%|          | 6/1000 [09:57<27:22:02, 99.12s/it]   1%|          | 7/1000 [11:48<28:21:35, 102.82s/it]  1%|          | 8/1000 [13:17<27:06:02, 98.35s/it]   1%|          | 9/1000 [14:25<24:29:15, 88.96s/it]  1%|          | 10/1000 [15:53<24:22:51, 88.66s/it]  1%|          | 11/1000 [18:10<28:24:15, 103.39s/it]  1%|          | 12/1000 [19:42<27:29:07, 100.15s/it]  1%|▏         | 13/1000 [21:22<27:22:16, 99.83s/it]   1%|▏         | 14/1000 [22:51<26:28:52, 96.69s/it]  2%|▏         | 15/1000 [24:53<28:32:58, 104.34s/it]  2%|▏         | 16/1000 [26:50<29:33:17, 108.13s/it]slurmstepd: error: *** JOB 33884066 ON cs126 CANCELLED AT 2023-05-25T08:10:25 ***
